
### 解决异常 Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys [exception, method, status, uri]. The meter you are attempting to register has keys [method, status, uri].
management:
  metrics:
    web:
      server:
        auto-time-requests: false

